version: '3.4'

services:
  greysendwebsite:
    platform: linux/x86_64
    image: greysendwebsite
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      SECRET_KEY: "django-insecure-+(l4b_3&z9&g=7na=#*1ntg4)w_7&8@*a9@fag_l_1(+z+k=xf"
      POSTGRES_DB: grey_send_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: asdf1234
      POSTGRES_HOST: postgres
    ports:
      - 8002:8002
    depends_on:
      - postgres
  postgres:
    platform: linux/x86_64
    image: postgres:14.7
    restart: always
    environment:
      POSTGRES_PASSWORD: asdf1234
      POSTGRES_USER: admin
      POSTGRES_DB: grey_send_db
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data/

volumes:
  postgres-data:



